initial code for stir bar motor
ShyavanS/McMaster_Chem-E_Car_23-24 pull request #3
Opened 2024-01-15 17:05 UTC by aithihya-k

speed is set to 80% and PWM pins are 5 and 6

2024-01-15 17:18 UTC, ShyavanS requested changes
Looks good, but maybe use a different variable name than motorPin1 & 2. we'll have multiple motors in the code, so a less generic name would be better. Perhaps stirPin1 & 2? Or anything else you think makes more sense. Apart from that, I think it should be good to merge.

2024-01-15 17:57 UTC, ShyavanS requested changes
Didn't notice this in my first review, but both pins shouldn't be set to PWM. You can take a look at the DRV8833 datasheet for this, there's a logic table representing what each setting does to the motor. I'm attaching it here. For the stir bar, I think running in forward PWM & coast (fast decay mode) would be good. So use the settings that correspond to that. It is probably worth noting though that the direction the motor spins will be dependent on how we solder & wire it, so we'll have to swap the direction in software if it does end up spinning in the wrong direction by changing from the forward to reverse control mode depending on how it ends up. In any case, the direction the motor spins is more important for the drive than the stirring, so it may not even matter for this application. The only thing important here is the coasting functionality to keep stirring the mixture, while with drive, we want it to brake to stop as close to the set distance as possible.

<img width="275" alt="image" src="https://github.com/ShyavanS/McMaster_Chem-E_Car_23-24/assets/35411334/e0a4a260-da10-4379-bf78-c0bd48a978cd">

2024-01-23 18:21 UTC, ShyavanS approved these changes
Looks good now, you should be good to merge, but there are some conflicts. Just make sure when you merge to keep both and then we can edit/update the main branch to remove the duplicate lines. If you can't figure it out, we can get on a call sometime tomorrow.

2024-01-30 00:16 UTC, batrap5 approved these changes

2024-01-30 00:31 UTC, merged