PID functionality
ShyavanS/McMaster_Chem-E_Car_23-24 pull request #8
Opened 2024-02-06 00:57 UTC by AmanRV

Here is the PID logic I implemented. I am using a library- "PID_v1_bc.h" which does most of the actual calculations already. As of right now, stuff like the P,I,D weighting constants are just temporarily set to 0.3, because it needs to be adjusted through testing. The basic functionality is that the program sends the read Z value to the function, it does the PID calculations and returns a correction between -128 and 128 (to move left or right). Then I take this correction value and increase the speed of the left or right wheel to correct the direction through the offset. Ex. If it needs to correct and turn left, it should be a negative value like -50. It will add 50 speed to the right wheel to get it to turn left.

Let me know if there are any issues with the logic or code, I will work on fixing it

2024-02-06 18:11 UTC, ShyavanS requested changes
A couple of things. Where do you call PID_loop()? I don't see it called anywhere under the main loop so I don't think it will ever run. You can remove the buffer zone if statement under PID_loop() and for now, set the speed to 50% when calling drive forward so that we don't have to worry about sending it a speed greater than 256. Other than that it looks good. I assume everytime PID_loop is called it will update the offset and reference the updated value for zAngle right? As for the Kp, Ki, and Kd values, I know they have to be tuned with trial and error, but where did you get the temporary values of 0.3 for each from? Start by setting Ki and Kd to zero for this iteration of the code, to tune, we start by only adjusting Kp until it starts overshooting. Then when we actually test things out, we'll adjust those accordingly.

2024-02-06 20:15 UTC, AmanRV commented
I forgot to add the PID function to the main loop, I will do that now. As for the 0.3 values, I also just set them randomly as we haven't done any testing. I will change them to 1,0,0.

When the PID object is initialized, it gets the zAngle, output, and goal angle as a pointer, so I think that it always have the most updated values. Whenever PID_loop gets called it should update the offsets with the most recent zAngle. I will double check this with the library source code to confirm as well.

2024-02-06 20:39 UTC, ShyavanS approved these changes
Looks good now.

2024-02-08 22:47 UTC, batrap5 approved these changes

2024-02-08 23:01 UTC, merged